# Add 'area:translation' label to any changes within following folders or any subfolders
area:translation:
- changed-files:
  - any-glob-to-any-file: [
      'docs/translations/**',
      'frontend/src/components/templates/translations/**',
      'frontend/content/**'
    ]
