version: "2"

tasks:
  default:
    deps: [build]
    cmds:
      - ./server.exe
    sources:
      - server/**/*.go

  build:
    cmds:
      - go build -o server.exe -ldflags="-X 'github.com/openmultiplayer/web/server/src/version.Version={{.VERSION}}'" ./server/
    vars:
      VERSION:
        sh: git describe --always --dirty --tags

  services:
    cmds:
      - docker-compose -f .\docker-compose.dev.yml up -d

  generate:
    cmds:
      # Calling the Go generator from the Prisma CLI is not supported yet...
      # - npx @prisma/cli generate
      # so we call it directly:
      - go run github.com/prisma/prisma-client-go generate
      # Also generate TypeScript type declarations from some backend structs.
      - go run types.go

  docsindex:
    cmds:
      - go run ./server/indexbuilder/main.go

  migrate:
    cmds:
      - npx prisma migrate dev

  dbuild:
    cmds:
      - docker build -t southclaws/openmp-index .

  upload-assets:
    dir: frontend/public
    cmds:
      - mc cp --recursive images omp/assets

  build-email-templates:
    dir: emails
    cmds:
      - npm run build
